server:
  port: 8080

spring:
  datasource:
    username: root
    password: Hh199596
    url: jdbc:mysql://192.168.202.128:3306/yxt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/  # 页面映射路径
    suffix: .html # 试图后的后缀
    mode: HTML5 # 模板模式

  # 其他具体配置可参考org.springframework.boot.autoconfigure.thymeleaf.ThymeleafProperties
  # 上面的配置实际上就是注入该类的属性值

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package:

#showSql
logging:
  level:
    com:
      hdc:
        yxt:
          mapper: debug

